### ISSUE TITLE
  dateList.setAdapter(new DefaultDateAdapter(start, end, defaultDate));

### ISSUE THREAD

**Issue by walaagomaa18** [rspective/PagerDatePicker#13]
java.lang.ArrayIndexOutOfBoundsException: length=10956; index=-1
                                                                                       at java.util.ArrayList.get(ArrayList.java:310)
                                                                                       at pl.rspective.pagerdatepicker.adapter.AbsDateAdapter.setSelectedDate(AbsDateAdapter.java:81)
                                                                                       at pl.rspective.pagerdatepicker.adapter.AbsDateAdapter.<init>(AbsDateAdapter.java:56)
                                                                                       at pl.rspective.pagerdatepicker.sample.custom.CustomDateAdapter.<init>(CustomDateAdapter.java:0)
                                                                                       at pl.rspective.pagerdatepicker.sample.ui.fragments.DatePickerCustomFragment.onViewCreated(DatePickerCustomFragment.java:61)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1123)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
                                                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
                                                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
                                                                                       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:532)
                                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by AndroidSources** [comment]
did you get a solution for this?

**Comment by AndroidSources** [comment]
did you find a solution for this bug? Kindly help me
